import type { AIProviderPreset } from './types'

// 预设供应商列表
export const AI_PROVIDER_PRESETS: AIProviderPreset[] = [
  {
    id: 'deepseek',
    name: 'DeepSeek',
    baseUrl: 'https://api.deepseek.com',
    defaultModel: 'deepseek-v4-flash',
    availableModels: [
      { id: 'deepseek-v4-flash', name: 'DeepSeek V4 Flash', maxTokens: 8192 },
      { id: 'deepseek-v4-pro', name: 'DeepSeek V4 Pro', maxTokens: 8192 },
      { id: 'deepseek-chat', name: 'DeepSeek Chat (旧版，即将弃用)', maxTokens: 8192 },
      { id: 'deepseek-reasoner', name: 'DeepSeek Reasoner (旧版，即将弃用)', maxTokens: 8192 },
    ],
    website: 'https://platform.deepseek.com',
    description: '国产高性价比大模型，V4系列性能更强',
    apiKeyPlaceholder: 'sk-...',
    apiKeyUrl: 'https://platform.deepseek.com/api_keys',
  },
  {
    id: 'openai',
    name: 'OpenAI',
    baseUrl: 'https://api.openai.com/v1',
    defaultModel: 'gpt-4o-mini',
    availableModels: [
      { id: 'gpt-4o', name: 'GPT-4o', maxTokens: 4096 },
      { id: 'gpt-4o-mini', name: 'GPT-4o Mini', maxTokens: 4096 },
      { id: 'gpt-4-turbo', name: 'GPT-4 Turbo', maxTokens: 4096 },
      { id: 'gpt-3.5-turbo', name: 'GPT-3.5 Turbo', maxTokens: 4096 },
    ],
    website: 'https://platform.openai.com',
    description: '业界领先的AI模型，英文能力优秀',
    apiKeyPlaceholder: 'sk-...',
    apiKeyUrl: 'https://platform.openai.com/api-keys',
  },
  {
    id: 'moonshot',
    name: 'Moonshot (Kimi)',
    baseUrl: 'https://api.moonshot.cn/v1',
    defaultModel: 'moonshot-v1-8k',
    availableModels: [
      { id: 'moonshot-v1-8k', name: 'Moonshot V1 8K', maxTokens: 4096 },
      { id: 'moonshot-v1-32k', name: 'Moonshot V1 32K', maxTokens: 4096 },
      { id: 'moonshot-v1-128k', name: 'Moonshot V1 128K', maxTokens: 4096 },
    ],
    website: 'https://platform.moonshot.cn',
    description: '支持超长上下文，适合长播客转录',
    apiKeyPlaceholder: 'sk-...',
    apiKeyUrl: 'https://platform.moonshot.cn/console/api-keys',
  },
  {
    id: 'zhipu',
    name: '智谱AI (GLM)',
    baseUrl: 'https://open.bigmodel.cn/api/paas/v4',
    defaultModel: 'glm-4-flash',
    availableModels: [
      { id: 'glm-4', name: 'GLM-4', maxTokens: 4096 },
      { id: 'glm-4-flash', name: 'GLM-4 Flash (免费)', maxTokens: 4096 },
      { id: 'glm-4-long', name: 'GLM-4 Long', maxTokens: 4096 },
      { id: 'glm-4-air', name: 'GLM-4 Air', maxTokens: 4096 },
    ],
    website: 'https://open.bigmodel.cn',
    description: '清华系大模型，GLM-4 Flash 免费使用',
    apiKeyPlaceholder: 'xxx.yyy',
    apiKeyUrl: 'https://open.bigmodel.cn/usercenter/apikeys',
  },
  {
    id: 'qwen',
    name: '通义千问 (Qwen)',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    defaultModel: 'qwen-turbo',
    availableModels: [
      { id: 'qwen-turbo', name: 'Qwen Turbo', maxTokens: 4096 },
      { id: 'qwen-plus', name: 'Qwen Plus', maxTokens: 4096 },
      { id: 'qwen-max', name: 'Qwen Max', maxTokens: 4096 },
      { id: 'qwen-long', name: 'Qwen Long', maxTokens: 4096 },
    ],
    website: 'https://dashscope.aliyun.com',
    description: '阿里云大模型，与OpenAI兼容接口',
    apiKeyPlaceholder: 'sk-...',
    apiKeyUrl: 'https://dashscope.console.aliyun.com/apiKey',
  },
  {
    id: 'yi',
    name: '零一万物 (Yi)',
    baseUrl: 'https://api.lingyiwanwu.com/v1',
    defaultModel: 'yi-lightning',
    availableModels: [
      { id: 'yi-lightning', name: 'Yi Lightning', maxTokens: 4096 },
      { id: 'yi-medium', name: 'Yi Medium', maxTokens: 4096 },
      { id: 'yi-large', name: 'Yi Large', maxTokens: 4096 },
    ],
    website: 'https://platform.lingyiwanwu.com',
    description: '李开复创办的AI公司，性价比高',
    apiKeyPlaceholder: '...',
    apiKeyUrl: 'https://platform.lingyiwanwu.com/apikeys',
  },
  {
    id: 'minimax',
    name: 'MiniMax',
    baseUrl: 'https://api.minimax.chat/v1',
    defaultModel: 'abab6.5s-chat',
    availableModels: [
      { id: 'abab6.5s-chat', name: 'ABAB 6.5s', maxTokens: 4096 },
      { id: 'abab6.5-chat', name: 'ABAB 6.5', maxTokens: 4096 },
      { id: 'abab5.5-chat', name: 'ABAB 5.5', maxTokens: 4096 },
    ],
    website: 'https://platform.minimaxi.com',
    description: '海螺AI背后的大模型，中文对话能力强',
    apiKeyPlaceholder: 'eyJ...',
    apiKeyUrl: 'https://platform.minimaxi.com/user-center/basic-information/interface-key',
  },
]
